mutation ReverseTransaction($input: ReverseTransactionInput!) {
  reverseTransaction(input: $input) {
    clientMutationId
    reversal {
        __typename
        ... on Refund {
            ...refundFields
        }
        ... on Transaction {
            ...transactionFields
        }
    }
  }
}
