package webreferences2.ECommerceProxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2015-04-21T11:39:10.279Z
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IECommerce")
@XmlSeeAlso({ObjectFactory.class})
public interface IECommerce {

    @Action(input = "http://tempuri.org/IECommerce/RemoveAbandonedBasket", output = "http://tempuri.org/IECommerce/RemoveAbandonedBasketResponse")
    @RequestWrapper(localName = "RemoveAbandonedBasket", targetNamespace = "http://tempuri.org/", className = "webreferences2.ECommerceProxy.RemoveAbandonedBasket")
    @WebMethod(operationName = "RemoveAbandonedBasket", action = "http://tempuri.org/IECommerce/RemoveAbandonedBasket")
    @ResponseWrapper(localName = "RemoveAbandonedBasketResponse", targetNamespace = "http://tempuri.org/", className = "webreferences2.ECommerceProxy.RemoveAbandonedBasketResponse")
    public void removeAbandonedBasket(
        @WebParam(name = "jsonAbandonedBasket", targetNamespace = "http://tempuri.org/")
        java.lang.String jsonAbandonedBasket
    );

    @Action(input = "http://tempuri.org/IECommerce/SynchronizeAbandonedBasket", output = "http://tempuri.org/IECommerce/SynchronizeAbandonedBasketResponse")
    @RequestWrapper(localName = "SynchronizeAbandonedBasket", targetNamespace = "http://tempuri.org/", className = "webreferences2.ECommerceProxy.SynchronizeAbandonedBasket")
    @WebMethod(operationName = "SynchronizeAbandonedBasket", action = "http://tempuri.org/IECommerce/SynchronizeAbandonedBasket")
    @ResponseWrapper(localName = "SynchronizeAbandonedBasketResponse", targetNamespace = "http://tempuri.org/", className = "webreferences2.ECommerceProxy.SynchronizeAbandonedBasketResponse")
    public void synchronizeAbandonedBasket();

    @Action(input = "http://tempuri.org/IECommerce/AddOrder", output = "http://tempuri.org/IECommerce/AddOrderResponse")
    @RequestWrapper(localName = "AddOrder", targetNamespace = "http://tempuri.org/", className = "webreferences2.ECommerceProxy.AddOrder")
    @WebMethod(operationName = "AddOrder", action = "http://tempuri.org/IECommerce/AddOrder")
    @ResponseWrapper(localName = "AddOrderResponse", targetNamespace = "http://tempuri.org/", className = "webreferences2.ECommerceProxy.AddOrderResponse")
    public void addOrder(
        @WebParam(name = "jsonOrder", targetNamespace = "http://tempuri.org/")
        java.lang.String jsonOrder
    );

    @Action(input = "http://tempuri.org/IECommerce/SynchronizeOrders", output = "http://tempuri.org/IECommerce/SynchronizeOrdersResponse")
    @RequestWrapper(localName = "SynchronizeOrders", targetNamespace = "http://tempuri.org/", className = "webreferences2.ECommerceProxy.SynchronizeOrders")
    @WebMethod(operationName = "SynchronizeOrders", action = "http://tempuri.org/IECommerce/SynchronizeOrders")
    @ResponseWrapper(localName = "SynchronizeOrdersResponse", targetNamespace = "http://tempuri.org/", className = "webreferences2.ECommerceProxy.SynchronizeOrdersResponse")
    public void synchronizeOrders(
        @WebParam(name = "exportAll", targetNamespace = "http://tempuri.org/")
        java.lang.Boolean exportAll
    );

    @Action(input = "http://tempuri.org/IECommerce/SynchronizeProducts", output = "http://tempuri.org/IECommerce/SynchronizeProductsResponse")
    @RequestWrapper(localName = "SynchronizeProducts", targetNamespace = "http://tempuri.org/", className = "webreferences2.ECommerceProxy.SynchronizeProducts")
    @WebMethod(operationName = "SynchronizeProducts", action = "http://tempuri.org/IECommerce/SynchronizeProducts")
    @ResponseWrapper(localName = "SynchronizeProductsResponse", targetNamespace = "http://tempuri.org/", className = "webreferences2.ECommerceProxy.SynchronizeProductsResponse")
    public void synchronizeProducts(
        @WebParam(name = "exportAll", targetNamespace = "http://tempuri.org/")
        java.lang.Boolean exportAll
    );

    @Action(input = "http://tempuri.org/IECommerce/AddCustomer", output = "http://tempuri.org/IECommerce/AddCustomerResponse")
    @RequestWrapper(localName = "AddCustomer", targetNamespace = "http://tempuri.org/", className = "webreferences2.ECommerceProxy.AddCustomer")
    @WebMethod(operationName = "AddCustomer", action = "http://tempuri.org/IECommerce/AddCustomer")
    @ResponseWrapper(localName = "AddCustomerResponse", targetNamespace = "http://tempuri.org/", className = "webreferences2.ECommerceProxy.AddCustomerResponse")
    public void addCustomer(
        @WebParam(name = "jsonCustomer", targetNamespace = "http://tempuri.org/")
        java.lang.String jsonCustomer
    );

    @Action(input = "http://tempuri.org/IECommerce/UploadSettings", output = "http://tempuri.org/IECommerce/UploadSettingsResponse")
    @RequestWrapper(localName = "UploadSettings", targetNamespace = "http://tempuri.org/", className = "webreferences2.ECommerceProxy.UploadSettings")
    @WebMethod(operationName = "UploadSettings", action = "http://tempuri.org/IECommerce/UploadSettings")
    @ResponseWrapper(localName = "UploadSettingsResponse", targetNamespace = "http://tempuri.org/", className = "webreferences2.ECommerceProxy.UploadSettingsResponse")
    public void uploadSettings();

    @Action(input = "http://tempuri.org/IECommerce/AddAbandonedBasket", output = "http://tempuri.org/IECommerce/AddAbandonedBasketResponse")
    @RequestWrapper(localName = "AddAbandonedBasket", targetNamespace = "http://tempuri.org/", className = "webreferences2.ECommerceProxy.AddAbandonedBasket")
    @WebMethod(operationName = "AddAbandonedBasket", action = "http://tempuri.org/IECommerce/AddAbandonedBasket")
    @ResponseWrapper(localName = "AddAbandonedBasketResponse", targetNamespace = "http://tempuri.org/", className = "webreferences2.ECommerceProxy.AddAbandonedBasketResponse")
    public void addAbandonedBasket(
        @WebParam(name = "jsonAbandonedBasket", targetNamespace = "http://tempuri.org/")
        java.lang.String jsonAbandonedBasket
    );

    @Action(input = "http://tempuri.org/IECommerce/SynchronizeCustomers", output = "http://tempuri.org/IECommerce/SynchronizeCustomersResponse")
    @RequestWrapper(localName = "SynchronizeCustomers", targetNamespace = "http://tempuri.org/", className = "webreferences2.ECommerceProxy.SynchronizeCustomers")
    @WebMethod(operationName = "SynchronizeCustomers", action = "http://tempuri.org/IECommerce/SynchronizeCustomers")
    @ResponseWrapper(localName = "SynchronizeCustomersResponse", targetNamespace = "http://tempuri.org/", className = "webreferences2.ECommerceProxy.SynchronizeCustomersResponse")
    public void synchronizeCustomers(
        @WebParam(name = "exportAll", targetNamespace = "http://tempuri.org/")
        java.lang.Boolean exportAll
    );
}
