mutation AuthorizePayPalAccount($input: AuthorizePayPalAccountInput!) {
  authorizePayPalAccount(input: $input) {
    clientMutationId
    transaction {
      ...transactionFields
    }
    billingAgreementWithPurchasePaymentMethod {
        ...paymentMethodFields
    }
  }
}
