mutation ChargePayPalAccount($input: ChargePayPalAccountInput!) {
  chargePayPalAccount(input: $input) {
    clientMutationId
    transaction {
      ...transactionFields
    }
    billingAgreementWithPurchasePaymentMethod {
        ...paymentMethodFields
    }
  }
}
